"""patient accounts + reschedule cutoff

Revision ID: 0f6a68744b31
Revises: 75b75e78a9cb
Create Date: 2026-07-28 15:27:14.102595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6a68744b31'
down_revision: Union[str, Sequence[str], None] = '75b75e78a9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_otp_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mobile_e164', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mobile_e164', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('mobile_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failed_login_count', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_e164')
    )
    op.add_column('clinic_settings', sa.Column('reschedule_cutoff_minutes', sa.SmallInteger(), nullable=False, server_default='180'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic_settings', 'reschedule_cutoff_minutes')
    op.drop_table('patient_accounts')
    op.drop_table('account_otp_challenges')
    # ### end Alembic commands ###
