"""initial schema

Revision ID: 35a167a33088
Revises: 
Create Date: 2026-07-20 12:51:30.349010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35a167a33088'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_price_estimate', sa.Boolean(), nullable=False),
    sa.Column('appropriate_for', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('included', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'PRACTITIONER', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_reference', sa.String(length=32), nullable=False),
    sa.Column('practitioner_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('patient_full_name', sa.String(length=255), nullable=False),
    sa.Column('patient_email', sa.String(length=255), nullable=False),
    sa.Column('patient_phone', sa.String(length=64), nullable=False),
    sa.Column('patient_notes', sa.String(length=1000), nullable=True),
    sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('display_timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('SLOT_HELD', 'PENDING', 'CONFIRMED', 'RESCHEDULED', 'CANCELLED_BY_PATIENT', 'CANCELLED_BY_PRACTITIONER', 'COMPLETED', 'NO_SHOW', 'EXPIRED', name='appointment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['practitioner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_public_reference'), 'appointments', ['public_reference'], unique=True)
    op.create_table('availability_exceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practitioner_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=True),
    sa.Column('end_minute', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practitioner_id', 'date')
    )
    op.create_table('weekly_availability_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practitioner_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['practitioner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_availability_rules')
    op.drop_table('availability_exceptions')
    op.drop_index(op.f('ix_appointments_public_reference'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
