"""core schema

Revision ID: 75b75e78a9cb
Revises: 0001_extensions
Create Date: 2026-07-27 15:48:53.612336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75b75e78a9cb'
down_revision: Union[str, Sequence[str], None] = '0001_extensions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clinic_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinic_name', sa.String(length=150), nullable=False),
    sa.Column('clinic_phone_e164', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('slot_duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('cancellation_cutoff_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('video_join_early_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('tele_reminder_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('booking_enabled', sa.Boolean(), nullable=False),
    sa.Column('current_terms_version', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_admin_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_created', 'audit_events', ['actor_admin_id', 'created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('qualification', sa.String(length=250), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_user_id')
    )
    op.create_table('availability_slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_status', sa.String(length=20), nullable=False),
    sa.Column('blocked_reason', sa.String(length=250), nullable=True),
    sa.Column('created_by_admin_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    postgresql.ExcludeConstraint((sa.literal_column('doctor_id'), '='), (sa.literal_column("tstzrange(start_at, end_at, '[)')"), '&&'), where=sa.text('deleted_at IS NULL'), using='gist', name='ex_no_overlapping_slots'),
    sa.CheckConstraint("end_at = start_at + interval '30 minutes'", name='ck_slot_is_30_minutes'),
    sa.CheckConstraint('end_at > start_at', name='ck_slot_end_after_start'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slots_doctor_start', 'availability_slots', ['doctor_id', 'start_at'], unique=False)
    op.create_index('ix_slots_status_start', 'availability_slots', ['base_status', 'start_at'], unique=False)
    op.create_table('booking_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slot_id', sa.Uuid(), nullable=False),
    sa.Column('consultation_type', sa.String(length=30), nullable=False),
    sa.Column('patient_name', sa.String(length=150), nullable=False),
    sa.Column('mobile_e164', sa.String(length=16), nullable=False),
    sa.Column('sms_consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terms_version', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("mobile_e164 ~ '^\\+91[6-9][0-9]{9}$'", name='ck_booking_mobile_e164'),
    sa.ForeignKeyConstraint(['slot_id'], ['availability_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_booking_hold_expires', 'booking_requests', ['hold_expires_at'], unique=False)
    op.create_index('ix_booking_mobile_created', 'booking_requests', ['mobile_e164', 'created_at'], unique=False)
    op.create_index('ix_booking_slot_status', 'booking_requests', ['slot_id', 'status'], unique=False)
    op.create_index('uq_active_booking_request_per_slot', 'booking_requests', ['slot_id'], unique=True, postgresql_where=sa.text("status IN ('pending_otp', 'otp_verified')"))
    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('slot_id', sa.Uuid(), nullable=False),
    sa.Column('booking_request_id', sa.Uuid(), nullable=False),
    sa.Column('patient_name', sa.String(length=150), nullable=False),
    sa.Column('mobile_e164', sa.String(length=16), nullable=False),
    sa.Column('consultation_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('teleconsultation_phone_e164', sa.String(length=16), nullable=True),
    sa.Column('sms_consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terms_version', sa.String(length=30), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_show_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reschedule_count', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("mobile_e164 ~ '^\\+91[6-9][0-9]{9}$'", name='ck_appt_mobile_e164'),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['availability_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference'),
    sa.UniqueConstraint('booking_request_id')
    )
    op.create_index('ix_appt_doctor_status', 'appointments', ['doctor_id', 'status'], unique=False)
    op.create_index('ix_appt_mobile', 'appointments', ['mobile_e164'], unique=False)
    op.create_index('ix_appt_slot', 'appointments', ['slot_id'], unique=False)
    op.create_index('ix_appt_status', 'appointments', ['status'], unique=False)
    op.create_index('uq_active_appointment_per_slot', 'appointments', ['slot_id'], unique=True, postgresql_where=sa.text("status = 'confirmed'"))
    op.create_table('otp_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_request_id', sa.Uuid(), nullable=False),
    sa.Column('mobile_e164', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('otp_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.SmallInteger(), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('resend_count', sa.SmallInteger(), nullable=False),
    sa.Column('last_resend_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_booking_status', 'otp_challenges', ['booking_request_id', 'status'], unique=False)
    op.create_index('ix_otp_expires', 'otp_challenges', ['expires_at'], unique=False)
    op.create_index('ix_otp_mobile_created', 'otp_challenges', ['mobile_e164', 'created_at'], unique=False)
    op.create_table('appointment_access_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_access_token_appointment', 'appointment_access_tokens', ['appointment_id'], unique=False)
    op.create_index('ix_access_token_hash', 'appointment_access_tokens', ['token_hash'], unique=False)
    op.create_table('appointment_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_admin_id', sa.Uuid(), nullable=True),
    sa.Column('from_slot_id', sa.Uuid(), nullable=True),
    sa.Column('to_slot_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appt_event_appointment_created', 'appointment_events', ['appointment_id', 'created_at'], unique=False)
    op.create_table('meeting_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('join_url_encrypted', sa.Text(), nullable=True),
    sa.Column('meeting_identifier_encrypted', sa.Text(), nullable=True),
    sa.Column('set_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['set_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('booking_request_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('recipient_e164', sa.String(length=16), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=False),
    sa.Column('template_version', sa.String(length=30), nullable=False),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=150), nullable=True),
    sa.Column('attempt_count', sa.SmallInteger(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('deduplication_key', sa.String(length=150), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deduplication_key')
    )
    op.create_index('ix_notif_appointment_created', 'notifications', ['appointment_id', 'created_at'], unique=False)
    op.create_index('ix_notif_status_scheduled', 'notifications', ['status', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notif_status_scheduled', table_name='notifications')
    op.drop_index('ix_notif_appointment_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('meeting_details')
    op.drop_index('ix_appt_event_appointment_created', table_name='appointment_events')
    op.drop_table('appointment_events')
    op.drop_index('ix_access_token_hash', table_name='appointment_access_tokens')
    op.drop_index('ix_access_token_appointment', table_name='appointment_access_tokens')
    op.drop_table('appointment_access_tokens')
    op.drop_index('ix_otp_mobile_created', table_name='otp_challenges')
    op.drop_index('ix_otp_expires', table_name='otp_challenges')
    op.drop_index('ix_otp_booking_status', table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index('uq_active_appointment_per_slot', table_name='appointments', postgresql_where=sa.text("status = 'confirmed'"))
    op.drop_index('ix_appt_status', table_name='appointments')
    op.drop_index('ix_appt_slot', table_name='appointments')
    op.drop_index('ix_appt_mobile', table_name='appointments')
    op.drop_index('ix_appt_doctor_status', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('uq_active_booking_request_per_slot', table_name='booking_requests', postgresql_where=sa.text("status IN ('pending_otp', 'otp_verified')"))
    op.drop_index('ix_booking_slot_status', table_name='booking_requests')
    op.drop_index('ix_booking_mobile_created', table_name='booking_requests')
    op.drop_index('ix_booking_hold_expires', table_name='booking_requests')
    op.drop_table('booking_requests')
    op.drop_index('ix_slots_status_start', table_name='availability_slots')
    op.drop_index('ix_slots_doctor_start', table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_table('doctor_profiles')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_index('ix_audit_actor_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('clinic_settings')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
